# fly.toml file generated for translate-books on 2023-04-18T07:43:59+02:00

app = "translate-books"
primary_region = "cdg"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
